### ISSUE TITLE
Can't read LONG value

### ISSUE THREAD

**Issue by thiloboehm** [densmoe/JSON-Path-module#3]
I have the following part in a big JSON structure:

```json
{
  "features": {
    "lastSeen": {
      "definition": [
         "org.eclipse.vorto:Connectivity:1.0.0"
      ],
      "properties": {
        "status": {
          "value": {
            "value": 1581590492820,
            "unit": "timestamp"
          }
        }
      }
    }
  }
}
```

I try to read the timestamp value with _GetIntegerFromJSONByPath_ and
`$.features.lastSeen.properties.status.value.value`

But the return value is always empty.
How can I read this long value?

**Comment by densmoe** [comment]
I fixed the issue and uploaded a new version to the appstore. Let me know if you run into any issues.

**Comment by thiloboehm** [comment]
Thanks. Works like a charm.
