### ISSUE TITLE
Update to Mendix 8.18.10

### ISSUE THREAD

**Issue by rik-bos** [densmoe/JSON-Path-module#5]
Hi,

Would it be possible for you to update the project in the marketplace to Mendix 8 or 9 so it can be imported in Mendix 9 directly?

In the attachment you can find an updated version to Mendix 8.18.10 that I imported in Mendix 9.5.0 and confirmed that it works.

Thanks!

Rik Bos

[JSONPath-1.1.0-upgradedToMx-8.18.10.mpk.zip](https://github.com/densmoe/JSON-Path-module/files/7186976/JSONPath-1.1.0-upgradedToMx-8.18.10.mpk.zip)
os

**Comment by densmoe** [comment]
@rik-bos I published a new version that supports mx8+ and cleaned up some dependencies.

**Comment by rik-bos** [comment]
Awesome, thanks!
