### ISSUE TITLE
Vulnerabilities in json-path-2.6.0.jar

### ISSUE THREAD

**Issue by SanderDigital** [densmoe/JSON-Path-module#6]
See https://mvnrepository.com/artifact/com.jayway.jsonpath/json-path/2.6.0 for the vulnerabilities.

In the latest version 2.9 there are no vulnerabilities.

**Comment by SanderPostNL** [comment]
@densmoe Any plans on updating this java lib to 2.9? The 2.9 version does not have a nulnerabilitie.

https://mvnrepository.com/artifact/com.jayway.jsonpath/json-path/2.9.0

**Comment by SanderPostNL** [comment]
Note that you also have ot update json-smart to json-smart-2.5.0 and accessors-smart to accessors-smart-2.5.0

**Comment by densmoe** [comment]
I released 2 new versions to update dependencies and fix the vulnerability: 

- 2.0.3 fixes the vulnerability in mx8 LTS
- 2.1.0 upgraded the module to mx9 LTS

**Comment by SanderPostNL** [comment]
Nice work. Thanks
